# Generated by Django 4.0.4 on 2022-05-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_admin_user_is_patient_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tobecontacted',
            field=models.BooleanField(default=False, verbose_name='to be contacted status'),
        ),
    ]
